version: "3.9"
services:
  # World Simulator
  world_sim:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    command: python -m world_sim
  # Robot Allocator
  robot_allocator:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    command: python -m robot_allocator
    environment:
      - ZMQ_WORLD_SIM_HOST=world_sim
    depends_on:
      - order_processor # To set up IMS DB for getting tasks
  # Order Processor
  order_processor:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    command: python -m inventory_management_system.order_processor
  # Flask Web Server
  web_flask:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    ports:
      - 5000:5000
    command: python -m inventory_management_system.order_tracking_web_server
  # Node Web Server
  web_node:
    image: aw_node
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    ports:
      - 3000:3000
    environment:
      - ZMQ_HOST=world_sim
    command: npm --prefix ./env_visualizer install && node env_simulator/

volumes:
  # Requires a pre-existing volume with the base dir pointing to this cloned git repo
  vol1:
    external: true

networks:
  aw-net: