version: "3.8"
services:
  # World Simulator
  world-sim:
    image: elucidation/aw_base:latest
    volumes:
      - ./dev:/home/app/mapf/dev
    networks:
      - aw-net
    working_dir: /home/app/mapf/dev
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db # To publish world_t messages, robot positions, states etc.
    command: python -m world_sim reset
    logging:
      options:
        max-size: 10m
  # Robot Allocator
  robot-allocator:
    image: elucidation/aw_base:latest
    volumes:
      - ./dev:/home/app/mapf/dev
    networks:
      - aw-net
    working_dir: /home/app/mapf/dev
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - order-processor # To set up tasks etc.
      - redis-db # subscribe to world_t, pull/process tasks, robots etc.
    command: python -m robot_allocator
    logging:
      options:
        max-size: 10m
  # Order Processor
  order-processor:
    image: elucidation/aw_base:latest
    volumes:
      - ./dev:/home/app/mapf/dev
    networks:
      - aw-net
    working_dir: /home/app/mapf/dev
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db # Manage Orders/Stations/Tasks
    command: python -m inventory_management_system.order_processor reset
    logging:
      options:
        max-size: 10m
  # Fake Order Sender
  fake-order-sender:
    image: elucidation/aw_base:latest
    volumes:
      - ./dev:/home/app/mapf/dev
    networks:
      - aw-net
    working_dir: /home/app/mapf/dev
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db # Submit order requests
    command: python -m inventory_management_system.fake_order_sender -k 10 --max-item-id 47 -d 1
    logging:
      options:
        max-size: 10m
  # Node Web Server
  web-node:
    image: node:alpine
    volumes:
      - ./dev:/home/app/mapf/dev
    networks:
      - aw-net
    working_dir: /home/app/mapf/dev
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db # To subscribe to world_t messages
    command: /bin/sh -c "npm --prefix ./env_visualizer install && node env_visualizer/"
    logging:
      options:
        max-size: 10m
  # Redis DB
  redis-db:
    image: redis:alpine
    networks:
      - aw-net
    volumes:
      - ./dev/redis/data:/data
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    logging:
      options:
        max-size: 10m

networks:
  aw-net: