FROM node:alpine

WORKDIR /home/app/mapf-multiagent-robot-planning/dev/env_visualizer/
RUN npm install
RUN npm install zeromq@6.0.0-beta.16  # TODO : remove this extraneous step?
WORKDIR /home/app/mapf-multiagent-robot-planning/dev/

CMD ["node", "env_visualizer/"]