FROM node:alpine

WORKDIR /home/app/mapf-multiagent-robot-planning/dev/env_visualizer/

COPY ./dev/env_visualizer/package.json ./dev/env_visualizer/package-lock.json ./

RUN npm install

WORKDIR /home/app/mapf-multiagent-robot-planning/dev/

CMD ["node", "env_visualizer/"]
