FROM node:alpine

COPY ./dev/env_visualizer/package.json ./dev/env_visualizer/package-lock.json .
WORKDIR /home/app/mapf-multiagent-robot-planning/dev/env_visualizer/

RUN npm install

WORKDIR /home/app/mapf-multiagent-robot-planning/dev/

CMD ["node", "env_visualizer/"]