version: "3.8"
services:
  # World Simulator
  world-sim:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db # To publish world_t messages
    command: python -m world_sim
  # Robot Allocator
  robot-allocator:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - order-processor # To set up IMS DB for getting tasks
      - redis-db # To subscribe to world_t messages
    command: python -m robot_allocator
  # Order Processor
  order-processor:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    command: python -m inventory_management_system.order_processor
  # Flask Web Server
  web-flask:
    image: aw_base
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    ports:
      - 5000:5000
    command: python -m inventory_management_system.order_tracking_web_server
  # Node Web Server
  web-node:
    image: node:alpine
    volumes:
      - vol1:/home/app
    networks:
      - aw-net
    working_dir: /home/app/mapf-multiagent-robot-planning/dev
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis-db
      - IMS_URL=http://localhost:5000
    depends_on:
      - redis-db # To subscribe to world_t messages
    command: /bin/sh -c "npm --prefix ./env_visualizer install && node env_visualizer/"
  # Redis DB
  redis-db:
    image: redis:alpine
    networks:
      - aw-net
    volumes:
      - redis-vol:/data
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning

volumes:
  # Requires a pre-existing volume with the base dir pointing to this cloned git repo
  vol1:
    external: true
  redis-vol:
    external: true

networks:
  aw-net: