apiVersion: apps/v1
kind: Deployment
metadata:
  name: automated-warehouse
  labels:
    app: mapf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapf
  template:
    metadata:
      labels:
        app: mapf
    spec:
      hostname: automated-warehouse-pod
      # subdomain: redis-service
      initContainers:
      - name: setup-vol1-container
        command: ["/bin/sh","-c"]
        args: ["[ -d mapf ] && exit 0; apk add git && git clone https://github.com/Elucidation/mapf-multiagent-robot-planning/ mapf"]
        image: alpine
        workingDir: /home/app/
        volumeMounts:
        - mountPath: /home/app
          name: vol1
        - mountPath: /data
          name: vol-db
      containers:
        # Redis DB
        - name: redis-db
          args:
            - redis-server
            - --save
            - "60"
            - "1"
            - --loglevel
            - warning
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-vol
              mountPath: /data
        # World Sim
        - name: world-sim
          workingDir: /home/app/mapf/dev
          args:
            - python
            - -m
            - world_sim
            - reset
          image: elucidation/aw_base:latest
          volumeMounts:
            - name: vol1
              mountPath: /home/app
            - name: vol-db
              mountPath: /data
        # Order Processor
        - name: order-processor
          workingDir: /home/app/mapf/dev
          args:
            - python
            - -m
            - inventory_management_system.order_processor
            - reset
          image: elucidation/aw_base:latest
          volumeMounts:
            - name: vol1
              mountPath: /home/app
            - name: vol-db
              mountPath: /data
          # Robot Allocator
        - name: robot-allocator
          workingDir: /home/app/mapf/dev
          args:
            - python
            - -m
            - robot_allocator
          image: elucidation/aw_base:latest
          volumeMounts:
            - name: vol1
              mountPath: /home/app
            - name: vol-db
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: vol1 # Assumes /home/app/mapf has git dir
          persistentVolumeClaim:
            claimName: vol1-claim
        - name: redis-vol
          persistentVolumeClaim:
            claimName: redis-vol-claim
        - name: vol-db # Assumes /data has world/order db files
          persistentVolumeClaim:
            claimName: vol-db-claim
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: mapf
  clusterIP: None
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379