# Every morning pull the latest git updates from the google_kubernetes branch
apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-sync
spec:
  schedule: "0 3 * * *"  # runs every day at 3am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: git-sync
            image: k8s.gcr.io/git-sync:v3.1.5
            args:
            - -repo=https://github.com/Elucidation/mapf-multiagent-robot-planning.git
            - -branch=google_kubernetes
            - -depth=1
            - -dest=.
            volumeMounts:
            - name: git-volume
              mountPath: /home/app/mapf
          restartPolicy: OnFailure
          volumes:
          - name: git-volume
            persistentVolumeClaim:
              claimName: vol1-claim
