# Every morning at 3am sync the latest google_kubernetes branch to /home/app/git-sync/mapf
apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-sync
spec:
  schedule: "0 * * * *"  # runs every hour
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: git-sync-once
              image: k8s.gcr.io/git-sync/git-sync:v3.2.2
              securityContext:
                runAsUser: 0  # Run as root for permissions
              env:
                - name: GIT_SYNC_REPO
                  value: "https://github.com/Elucidation/mapf-multiagent-robot-planning.git"
                - name: GIT_SYNC_BRANCH
                  value: "google_kubernetes"
                - name: GIT_SYNC_DEPTH
                  value: "1"
                - name: GIT_SYNC_DEST
                  value: "mapf"
                - name: GIT_SYNC_ROOT
                  value: "/home/app/git-sync"
                - name: GIT_SYNC_ONE_TIME
                  value: "true"
              volumeMounts:
              - name: git-volume
                mountPath: /home/app
              resources:
                requests:
                  cpu: "0.1"
                  memory: "100Mi"
          containers:
            # This container sets env variable, which triggers deployment restart
            # Can look at the var via: kubectl set env deployment/automated-warehouse --list
            - name: kubectl-set-env
              image: bitnami/kubectl:latest
              env:
              - name: COMMIT_URL
                value: "https://api.github.com/repos/Elucidation/mapf-multiagent-robot-planning/commits/google_kubernetes"
              command: ["/bin/sh", "-c"]
              args: # sets RESTART_ to the latest commit date (if this changes it'll trigger deployment restart)
                - |
                  COMMIT_DATE=$(wget -qO- $COMMIT_URL | awk -F'\"' '/date/{print $4; exit}') && 
                  kubectl set env deployment/automated-warehouse RESTART_=$COMMIT_DATE && 
                  echo $COMMIT_DATE
              resources:
                requests:
                  cpu: "0.1"
                  memory: "100Mi"
          restartPolicy: Never
          volumes:
          - name: git-volume
            persistentVolumeClaim:
              claimName: vol1-claim
