apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-db-claim
spec:
  # volumeName: vol-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo