apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1-claim
spec:
  # volumeName: vol1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo